server.port: '8080'

spring:
  application.name: device-management
  datasource:
    url: jdbc:h2:./.data/algasensors-device-management-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: 'true'
      settings.web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

logging:
  level:
    org:
      hibernate:
        orm:
          connections:
            pooling: warn
